// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	incomeFieldNames          = builder.RawFieldNames(&Income{})
	incomeRows                = strings.Join(incomeFieldNames, ",")
	incomeRowsExpectAutoSet   = strings.Join(stringx.Remove(incomeFieldNames, "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`"), ",")
	incomeRowsWithPlaceHolder = strings.Join(stringx.Remove(incomeFieldNames, "`id`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`"), "=?,") + "=?"

	cacheIncomeIdPrefix = "cache:income:id:"
)

type (
	incomeModel interface {
		Insert(ctx context.Context, data *Income) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Income, error)
		Update(ctx context.Context, data *Income) error
		Delete(ctx context.Context, id int64) error
	}

	defaultIncomeModel struct {
		sqlc.CachedConn
		table string
	}

	Income struct {
		Id   int64  `db:"id"`
		Type string `db:"type"` // 收入类型
		Date string `db:"date"` // 日期
		Num  int64  `db:"num"`  // 当天收入
	}
)

func newIncomeModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultIncomeModel {
	return &defaultIncomeModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`income`",
	}
}

func (m *defaultIncomeModel) Delete(ctx context.Context, id int64) error {
	incomeIdKey := fmt.Sprintf("%s%v", cacheIncomeIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, incomeIdKey)
	return err
}

func (m *defaultIncomeModel) FindOne(ctx context.Context, id int64) (*Income, error) {
	incomeIdKey := fmt.Sprintf("%s%v", cacheIncomeIdPrefix, id)
	var resp Income
	err := m.QueryRowCtx(ctx, &resp, incomeIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", incomeRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultIncomeModel) Insert(ctx context.Context, data *Income) (sql.Result, error) {
	incomeIdKey := fmt.Sprintf("%s%v", cacheIncomeIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, incomeRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.Type, data.Date, data.Num)
	}, incomeIdKey)
	return ret, err
}

func (m *defaultIncomeModel) Update(ctx context.Context, data *Income) error {
	incomeIdKey := fmt.Sprintf("%s%v", cacheIncomeIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, incomeRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Type, data.Date, data.Num, data.Id)
	}, incomeIdKey)
	return err
}

func (m *defaultIncomeModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheIncomeIdPrefix, primary)
}

func (m *defaultIncomeModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", incomeRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultIncomeModel) tableName() string {
	return m.table
}
