// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	wechatFieldNames          = builder.RawFieldNames(&Wechat{})
	wechatRows                = strings.Join(wechatFieldNames, ",")
	wechatRowsExpectAutoSet   = strings.Join(stringx.Remove(wechatFieldNames, "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`"), ",")
	wechatRowsWithPlaceHolder = strings.Join(stringx.Remove(wechatFieldNames, "`id`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`"), "=?,") + "=?"
)

type (
	wechatModel interface {
		Insert(ctx context.Context, data *Wechat) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Wechat, error)
		Update(ctx context.Context, data *Wechat) error
		Delete(ctx context.Context, id int64) error
	}

	defaultWechatModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Wechat struct {
		Id   int64     `db:"id"`
		Date time.Time `db:"date"` // 日期
		Num  int64     `db:"num"`  // 微信关注数量
	}
)

func newWechatModel(conn sqlx.SqlConn) *defaultWechatModel {
	return &defaultWechatModel{
		conn:  conn,
		table: "`wechat`",
	}
}

func (m *defaultWechatModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultWechatModel) FindOne(ctx context.Context, id int64) (*Wechat, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", wechatRows, m.table)
	var resp Wechat
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWechatModel) Insert(ctx context.Context, data *Wechat) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, wechatRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Date, data.Num)
	return ret, err
}

func (m *defaultWechatModel) Update(ctx context.Context, data *Wechat) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, wechatRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Date, data.Num, data.Id)
	return err
}

func (m *defaultWechatModel) tableName() string {
	return m.table
}
