// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	accessFieldNames          = builder.RawFieldNames(&Access{})
	accessRows                = strings.Join(accessFieldNames, ",")
	accessRowsExpectAutoSet   = strings.Join(stringx.Remove(accessFieldNames, "`id`", "`update_time`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`"), ",")
	accessRowsWithPlaceHolder = strings.Join(stringx.Remove(accessFieldNames, "`id`", "`update_time`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`"), "=?,") + "=?"
)

type (
	accessModel interface {
		Insert(ctx context.Context, data *Access) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Access, error)
		Update(ctx context.Context, data *Access) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAccessModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Access struct {
		Id       int64     `db:"id"`
		Location string    `db:"location"` // 接入地点
		Date     time.Time `db:"date"`     // 接入日期
		Num      int64     `db:"num"`      // 接入数量
	}
)

func newAccessModel(conn sqlx.SqlConn) *defaultAccessModel {
	return &defaultAccessModel{
		conn:  conn,
		table: "`access`",
	}
}

func (m *defaultAccessModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAccessModel) FindOne(ctx context.Context, id int64) (*Access, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", accessRows, m.table)
	var resp Access
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAccessModel) Insert(ctx context.Context, data *Access) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, accessRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Location, data.Date, data.Num)
	return ret, err
}

func (m *defaultAccessModel) Update(ctx context.Context, data *Access) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, accessRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Location, data.Date, data.Num, data.Id)
	return err
}

func (m *defaultAccessModel) tableName() string {
	return m.table
}
